# Publish GitHub Pages
# azure-pipelines.yml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: |
    npm install
    npm build
    npm deploy
    git config --local user.name "mail@tmirwald.de"
    git config --local user.email "Tom Mirwald"
    git add .
    git commit -m "Publishing GitHub Pages  ***NO_CI***"
  displayName: 'Build and commit pages'

- task: DownloadSecureFile@1
  inputs:
    secureFile: deploy_key
  displayName: 'Get the deploy key'

- script: |
    mkdir ~/.ssh && mv $DOWNLOADSECUREFILE_SECUREFILEPATH ~/.ssh/id_rsa
    chmod 700 ~/.ssh && chmod 600 ~/.ssh/id_rsa
    ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts
    git remote set-url --push origin git@github.com:70mm1/azure-pipe-demo.git
    git push origin master
  displayName: 'Publish GitHub Pages'
