pool:
  vmImage: 'ubuntu-latest'

trigger:
- master

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    git config --global user.email "mail@tmirwald.de" 
    git config --global user.name "Tom Mirwald"
    npm install
    npm run build
    npx gh-pages --repo https://$(DEPLOY_TOKEN)@github.com/70mm1/azure-pipe-demo.git
  displayName: 'npm install and build'
 

  