variables:
  PUBLISHPASS: $(PUBLISHKEY)

trigger:
  - main

pool:
  vmImage: "ubuntu-latest"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "12.x"
    displayName: "Install Node.js"

  - task: DownloadSecureFile@1
    name: mySecureFile
    inputs:
      secureFile: "6312da48-b03b-4854-9e77-443c51702218"
      retryCount: "2"

  - task: InstallSSHKey@0
    inputs:
      knownHostsEntry: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGpXW7NIpEgwacaez6gvMO4Z8wZw4trVmeuGvHMYSOyW mail@tmirwald.de"
      sshPublicKey: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIGpXW7NIpEgwacaez6gvMO4Z8wZw4trVmeuGvHMYSOyW mail@tmirwald.de"
      sshPassphrase: "$(PUBLISHPASS)"
      sshKeySecureFile: "6312da48-b03b-4854-9e77-443c51702218"

  - script: |
      git config --global --add url."git@github.com:".insteadOf "https://github.com/"
      git config --local user.email "mail@tmirwald.de"
      git config --local user.name "70mm1"
      npm install --no-audit --progress=false      
      npm run deploy
    displayName: "npm install and deploy"
